name: Fix Image
on:
  push:
  workflow_dispatch:

jobs:
  fix_image:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
          lfs: true
          fetch-depth: 1

      - name: Fix Image
        shell: bash
        run: |
          set -euxo pipefail
          cp -f src/assets/principal.jpg.bak src/assets/principal.jpg

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
